// ============================================================
// OLOPA — gRPC Sender + Disk Spool
// ============================================================
// Receives BatchOutput from the Batcher and ships it to the
// backend ingest gateway over a persistent mTLS HTTP/2 gRPC
// stream. One long-lived stream per agent — no reconnect per
// batch.
//
// Backpressure contract (from backend ThrottleAck):
//   throttle_ratio = 0.0  → all clear, send at full rate
//   throttle_ratio > 0.0  → raise flush interval proportionally
//   throttle_ratio > 0.8  → activate disk spool
//   throttle_ratio = 1.0  → stop sending, spool everything
//
// Disk spool:
//   Append-only log: [u32 len BE][batch bytes] per entry.
//   Written when throttle_ratio > 0.8 or stream is unavailable.
//   Replayed FIFO when the backend recovers.
//   Max spool size enforced — oldest entries evicted if exceeded.
// ============================================================

use std::path::{Path, PathBuf};
use std::fs::{File, OpenOptions};
use std::io::{self, BufWriter, Read, Seek, SeekFrom, Write};
use std::sync::atomic::{AtomicU64, AtomicBool, Ordering};
use std::time::{Duration, Instant};
use bytes::Bytes;
use crossbeam_utils::CachePadded;
use tokio::sync::mpsc;
use tonic::transport::{Channel, ClientTlsConfig, Certificate, Identity};
use tonic::{Request, Streaming};

// Proto-generated types (placeholders — replace with prost-generated)
// In production: generated by build.rs from olopa.proto
mod proto {
    #[derive(Clone, prost::Message)]
    pub struct BatchFrame {
        #[prost(bytes = "bytes", tag = "1")]
        pub payload: bytes::Bytes,
        #[prost(uint64, tag = "2")]
        pub sequence: u64,
    }

    #[derive(Clone, prost::Message)]
    pub struct IngestAck {
        #[prost(uint32, tag = "1")]
        pub accepted: u32,
        #[prost(uint32, tag = "2")]
        pub rejected: u32,
        #[prost(uint32, tag = "3")]
        pub retry_after_ms: u32,
        #[prost(uint32, tag = "4")]
        pub suggested_batch_bytes: u32,
        #[prost(float, tag = "5")]
        pub throttle_ratio: f32,
    }
}

// ── Sender configuration ──────────────────────────────────────
#[derive(Clone, Debug)]
pub struct SenderConfig {
    pub endpoint:         String,          // "https://ingest.olopa.internal:443"
    pub ca_cert_path:     PathBuf,         // backend CA certificate (mTLS)
    pub client_cert_path: PathBuf,         // device identity certificate
    pub client_key_path:  PathBuf,         // device identity private key
    pub spool_path:       PathBuf,         // path for the append-only spool file
    pub spool_max_bytes:  u64,             // maximum spool file size (default 2 GB)
    pub connect_timeout:  Duration,        // initial connection timeout
    pub send_timeout:     Duration,        // per-batch send timeout
    pub max_retry_delay:  Duration,        // exponential backoff ceiling
}

impl Default for SenderConfig {
    fn default() -> Self {
        Self {
            endpoint:         "https://ingest.olopa.io:443".into(),
            ca_cert_path:     "/etc/olopa/ca.crt".into(),
            client_cert_path: "/etc/olopa/agent.crt".into(),
            client_key_path:  "/etc/olopa/agent.key".into(),
            spool_path:       "/var/lib/olopa/spool.bin".into(),
            spool_max_bytes:  2 * 1024 * 1024 * 1024, // 2 GB
            connect_timeout:  Duration::from_secs(10),
            send_timeout:     Duration::from_secs(30),
            max_retry_delay:  Duration::from_secs(60),
        }
    }
}

// ── BackpressureState — current view of backend health ───────
#[derive(Clone, Debug)]
pub struct BackpressureState {
    pub throttle_ratio:         f32,   // 0.0 = clear, 1.0 = full stop
    pub retry_after_ms:         u32,   // backend-suggested retry delay
    pub suggested_batch_bytes:  u32,   // backend-suggested batch size cap
    pub spooling:               bool,  // true when spool is active
    pub last_ack_at:            Instant,
}

impl Default for BackpressureState {
    fn default() -> Self {
        Self {
            throttle_ratio:        0.0,
            retry_after_ms:        0,
            suggested_batch_bytes: 4 * 1024 * 1024,
            spooling:              false,
            last_ack_at:           Instant::now(),
        }
    }
}

impl BackpressureState {
    // Should we spool instead of sending directly?
    pub fn should_spool(&self) -> bool {
        self.throttle_ratio > 0.8 || self.spooling
    }

    // Flush interval multiplier based on throttle_ratio.
    // throttle_ratio=0.5 → 1.5× normal interval.
    // throttle_ratio=0.8 → 4.0× normal interval.
    pub fn flush_interval_multiplier(&self) -> f32 {
        1.0 + self.throttle_ratio * 3.0 // 1.0 at 0.0 → 4.0 at 1.0
    }

    pub fn update_from_ack(&mut self, ack: &proto::IngestAck) {
        self.throttle_ratio        = ack.throttle_ratio.clamp(0.0, 1.0);
        self.retry_after_ms        = ack.retry_after_ms;
        self.suggested_batch_bytes = if ack.suggested_batch_bytes > 0 {
            ack.suggested_batch_bytes
        } else {
            4 * 1024 * 1024
        };
        self.spooling   = self.throttle_ratio > 0.8;
        self.last_ack_at = Instant::now();
    }
}

// ── DiskSpool — append-only log ──────────────────────────────
// Wire format per entry: [u32 len BE][batch bytes]
// On replay: read len, read that many bytes, decompress+send.
// On spool eviction (max size exceeded): truncate from the front
// by rewriting — in production use a circular file or two-file
// scheme; this implementation uses a simple seek-based approach.
pub struct DiskSpool {
    path:          PathBuf,
    writer:        BufWriter<File>,  // append writer — O_APPEND
    read_offset:   u64,              // where the replay reader is
    write_offset:  u64,              // current end of file
    max_bytes:     u64,

    // Metrics
    pub bytes_spooled:   CachePadded<AtomicU64>,
    pub bytes_replayed:  CachePadded<AtomicU64>,
    pub entries_spooled: CachePadded<AtomicU64>,
    pub entries_replayed:CachePadded<AtomicU64>,
}

impl DiskSpool {
    pub fn open(path: &Path, max_bytes: u64) -> io::Result<Self> {
        // Open or create the spool file.
        // O_APPEND ensures every write goes to the end atomically.
        let file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(path)?;

        let write_offset = file.metadata()?.len();

        // Read offset starts at the current end if this is a fresh open
        // (we don't replay old spool data from before the agent restarted
        // unless explicitly requested — that's a recovery mode operation).
        let read_offset = write_offset;

        Ok(Self {
            path: path.to_path_buf(),
            writer: BufWriter::with_capacity(64 * 1024, file),
            read_offset,
            write_offset,
            max_bytes,
            bytes_spooled:    CachePadded::new(AtomicU64::new(0)),
            bytes_replayed:   CachePadded::new(AtomicU64::new(0)),
            entries_spooled:  CachePadded::new(AtomicU64::new(0)),
            entries_replayed: CachePadded::new(AtomicU64::new(0)),
        })
    }

    // ── Write a batch to the spool ────────────────────────────
    // [u32 len BE][batch bytes]
    // BufWriter buffers up to 64KB — flushes automatically on full.
    // Explicit flush() called at end to ensure durability before ack.
    pub fn append(&mut self, batch: &[u8]) -> io::Result<()> {
        // Evict old entries if we're near the size limit
        if self.write_offset + batch.len() as u64 + 4 > self.max_bytes {
            self.evict_oldest(batch.len() as u64 + 4)?;
        }

        let len = batch.len() as u32;
        self.writer.write_all(&len.to_be_bytes())?;
        self.writer.write_all(batch)?;
        self.writer.flush()?; // ensure durability

        let entry_size = 4 + batch.len() as u64;
        self.write_offset += entry_size;

        self.bytes_spooled.fetch_add(batch.len() as u64, Ordering::Relaxed);
        self.entries_spooled.fetch_add(1, Ordering::Relaxed);
        Ok(())
    }

    // ── Read the next entry for replay ────────────────────────
    // Returns None when all entries have been replayed.
    // Advances read_offset forward.
    pub fn next_entry(&mut self) -> io::Result<Option<Vec<u8>>> {
        if self.read_offset >= self.write_offset {
            return Ok(None); // nothing left to replay
        }

        // Open a separate read handle (writer holds the append fd)
        let mut reader = File::open(&self.path)?;
        reader.seek(SeekFrom::Start(self.read_offset))?;

        // Read the 4-byte length prefix
        let mut len_buf = [0u8; 4];
        match reader.read_exact(&mut len_buf) {
            Ok(_)  => {}
            Err(e) if e.kind() == io::ErrorKind::UnexpectedEof => return Ok(None),
            Err(e) => return Err(e),
        }
        let len = u32::from_be_bytes(len_buf) as usize;

        // Read the entry body
        let mut body = vec![0u8; len];
        reader.read_exact(&mut body)?;

        self.read_offset += 4 + len as u64;
        self.bytes_replayed.fetch_add(len as u64, Ordering::Relaxed);
        self.entries_replayed.fetch_add(1, Ordering::Relaxed);
        Ok(Some(body))
    }

    // ── Evict oldest entries to make space ────────────────────
    // Simple strategy: move read_offset forward past old entries
    // until enough space is freed. The space is reclaimed by
    // truncating and rewriting the file (expensive but rare).
    // Production: use a circular buffer file or two-file rotation.
    fn evict_oldest(&mut self, needed: u64) -> io::Result<()> {
        let mut freed = 0u64;
        let mut reader = File::open(&self.path)?;
        let mut scan_offset = 0u64; // scan from the very beginning

        // Advance scan_offset past entries until we've freed enough
        while freed < needed && scan_offset < self.write_offset {
            reader.seek(SeekFrom::Start(scan_offset))?;
            let mut len_buf = [0u8; 4];
            if reader.read_exact(&mut len_buf).is_err() { break; }
            let entry_len = u32::from_be_bytes(len_buf) as u64;
            freed       += 4 + entry_len;
            scan_offset += 4 + entry_len;
        }

        if freed == 0 { return Ok(()); }

        // Read everything after the evicted entries
        let remaining_len = self.write_offset.saturating_sub(scan_offset);
        let mut remaining = vec![0u8; remaining_len as usize];
        reader.seek(SeekFrom::Start(scan_offset))?;
        reader.read_exact(&mut remaining)?;
        drop(reader);

        // Rewrite spool file without the evicted prefix
        let mut file = OpenOptions::new()
            .write(true)
            .truncate(true)
            .open(&self.path)?;
        file.write_all(&remaining)?;
        file.flush()?;
        drop(file);

        // Reopen append writer
        let new_file = OpenOptions::new()
            .append(true)
            .open(&self.path)?;
        self.writer       = BufWriter::with_capacity(64 * 1024, new_file);
        self.write_offset = remaining_len;
        self.read_offset  = self.read_offset.saturating_sub(scan_offset);

        Ok(())
    }

    // ── Reset replay cursor to beginning ─────────────────────
    // Used for recovery mode: replay the entire spool from scratch.
    pub fn reset_replay(&mut self) {
        self.read_offset = 0;
    }

    pub fn pending_bytes(&self) -> u64 {
        self.write_offset.saturating_sub(self.read_offset)
    }

    pub fn is_empty(&self) -> bool {
        self.pending_bytes() == 0
    }
}

// ── Sender — the gRPC streaming client ───────────────────────
pub struct Sender {
    config:      SenderConfig,
    bp:          BackpressureState,
    spool:       DiskSpool,
    sequence:    u64,          // monotonic sequence number per batch
    retry_delay: Duration,     // current exponential backoff delay

    // Stream handle — None when disconnected
    stream_tx:   Option<mpsc::Sender<proto::BatchFrame>>,

    // Metrics
    pub batches_sent:    CachePadded<AtomicU64>,
    pub batches_spooled: CachePadded<AtomicU64>,
    pub batches_acked:   CachePadded<AtomicU64>,
    pub send_errors:     CachePadded<AtomicU64>,
    pub reconnects:      CachePadded<AtomicU64>,
}

impl Sender {
    pub fn new(config: SenderConfig) -> io::Result<Self> {
        let spool = DiskSpool::open(&config.spool_path, config.spool_max_bytes)?;
        Ok(Self {
            spool,
            bp:           BackpressureState::default(),
            sequence:     0,
            retry_delay:  Duration::from_millis(100),
            stream_tx:    None,
            batches_sent:    CachePadded::new(AtomicU64::new(0)),
            batches_spooled: CachePadded::new(AtomicU64::new(0)),
            batches_acked:   CachePadded::new(AtomicU64::new(0)),
            send_errors:     CachePadded::new(AtomicU64::new(0)),
            reconnects:      CachePadded::new(AtomicU64::new(0)),
            config,
        })
    }

    // ── Send or spool a batch ─────────────────────────────────
    // The main entry point from the Batcher.
    // Decision:
    //   throttle_ratio > 0.8 → spool to disk
    //   stream available     → send directly
    //   stream unavailable   → spool to disk
    pub async fn send_or_spool(&mut self, batch: Bytes) -> SendResult {
        if self.bp.should_spool() || self.stream_tx.is_none() {
            return self.spool_batch(&batch);
        }
        self.send_direct(batch).await
    }

    // ── Direct send over the gRPC stream ─────────────────────
    async fn send_direct(&mut self, batch: Bytes) -> SendResult {
        let seq  = self.next_sequence();
        let frame = proto::BatchFrame { payload: batch.clone(), sequence: seq };

        match self.stream_tx.as_ref() {
            Some(tx) => match tx.try_send(frame) {
                Ok(_) => {
                    self.batches_sent.fetch_add(1, Ordering::Relaxed);
                    self.retry_delay = Duration::from_millis(100); // reset backoff
                    SendResult::Sent
                }
                Err(mpsc::error::TrySendError::Full(_)) => {
                    // Sender channel full — spool and signal backpressure
                    self.spool_batch(&batch)
                }
                Err(mpsc::error::TrySendError::Closed(_)) => {
                    // Stream disconnected — mark unavailable, spool
                    self.stream_tx = None;
                    self.send_errors.fetch_add(1, Ordering::Relaxed);
                    self.spool_batch(&batch)
                }
            }
            None => self.spool_batch(&batch),
        }
    }

    // ── Spool a batch to disk ─────────────────────────────────
    fn spool_batch(&mut self, batch: &[u8]) -> SendResult {
        match self.spool.append(batch) {
            Ok(_) => {
                self.batches_spooled.fetch_add(1, Ordering::Relaxed);
                SendResult::Spooled
            }
            Err(e) => {
                eprintln!("olopa spool: write error: {e}");
                self.send_errors.fetch_add(1, Ordering::Relaxed);
                SendResult::Dropped
            }
        }
    }

    // ── Replay spooled entries when backend recovers ──────────
    // Called by the recovery loop when throttle_ratio drops below 0.8.
    // Reads entries FIFO from the spool and sends them directly.
    // Stops if backpressure rises again mid-replay.
    pub async fn drain_spool(&mut self) -> io::Result<usize> {
        let mut replayed = 0;

        while !self.spool.is_empty() && !self.bp.should_spool() {
            match self.spool.next_entry()? {
                None => break,
                Some(entry) => {
                    let batch = Bytes::from(entry);
                    match self.send_direct(batch).await {
                        SendResult::Sent   => replayed += 1,
                        SendResult::Spooled => {
                            // Backpressure came back mid-replay — stop
                            break;
                        }
                        SendResult::Dropped => {
                            // Send failed — entry is lost (already consumed
                            // from spool read_offset). Log and continue.
                            self.send_errors.fetch_add(1, Ordering::Relaxed);
                        }
                    }
                }
            }
        }
        Ok(replayed)
    }

    // ── Establish mTLS gRPC connection ────────────────────────
    // Loads CA cert, client cert+key from disk.
    // Returns a Channel configured with mTLS.
    pub async fn connect(&mut self) -> Result<Channel, tonic::transport::Error> {
        let ca_cert     = std::fs::read(&self.config.ca_cert_path)
            .expect("CA cert not found");
        let client_cert = std::fs::read(&self.config.client_cert_path)
            .expect("client cert not found");
        let client_key  = std::fs::read(&self.config.client_key_path)
            .expect("client key not found");

        let tls = ClientTlsConfig::new()
            .ca_certificate(Certificate::from_pem(ca_cert))
            .identity(Identity::from_pem(client_cert, client_key));

        let channel = Channel::from_shared(self.config.endpoint.clone())
            .expect("invalid endpoint URI")
            .tls_config(tls)?
            .connect_timeout(self.config.connect_timeout)
            .timeout(self.config.send_timeout)
            // Keep-alive: ping every 30s, wait 10s for pong
            .http2_keep_alive_interval(Duration::from_secs(30))
            .keep_alive_timeout(Duration::from_secs(10))
            .keep_alive_while_idle(true)
            .connect()
            .await?;

        self.reconnects.fetch_add(1, Ordering::Relaxed);
        self.retry_delay = Duration::from_millis(100); // reset on success
        Ok(channel)
    }

    // ── Handle an IngestAck from the backend ─────────────────
    // Updates backpressure state. If throttle_ratio drops below 0.8
    // and spool is non-empty, signals the recovery loop.
    pub fn on_ack(&mut self, ack: proto::IngestAck) -> AckEffect {
        let was_spooling = self.bp.spooling;
        self.bp.update_from_ack(&ack);
        self.batches_acked.fetch_add(ack.accepted as u64, Ordering::Relaxed);

        if was_spooling && !self.bp.spooling && !self.spool.is_empty() {
            AckEffect::RecoveryNeeded // caller should start drain_spool()
        } else if self.bp.throttle_ratio > 0.0 {
            AckEffect::Throttled {
                multiplier: self.bp.flush_interval_multiplier(),
            }
        } else {
            AckEffect::Clear
        }
    }

    // ── Exponential backoff for reconnect attempts ────────────
    pub fn next_backoff(&mut self) -> Duration {
        let d = self.retry_delay;
        self.retry_delay = (self.retry_delay * 2).min(self.config.max_retry_delay);
        d
    }

    fn next_sequence(&mut self) -> u64 {
        let s = self.sequence;
        self.sequence += 1;
        s
    }

    pub fn stats(&self) -> SenderStats {
        SenderStats {
            batches_sent:      self.batches_sent.load(Ordering::Relaxed),
            batches_spooled:   self.batches_spooled.load(Ordering::Relaxed),
            batches_acked:     self.batches_acked.load(Ordering::Relaxed),
            send_errors:       self.send_errors.load(Ordering::Relaxed),
            reconnects:        self.reconnects.load(Ordering::Relaxed),
            throttle_ratio:    self.bp.throttle_ratio,
            spooling:          self.bp.spooling,
            spool_pending_bytes: self.spool.pending_bytes(),
        }
    }
}

// ── AckEffect — what the caller should do after an ack ───────
#[derive(Debug, PartialEq)]
pub enum AckEffect {
    Clear,                         // all good, send at full rate
    Throttled { multiplier: f32 }, // raise flush interval
    RecoveryNeeded,                // backend recovered, drain spool
}

// ── SendResult — outcome of send_or_spool() ──────────────────
#[derive(Debug, PartialEq)]
pub enum SendResult {
    Sent,    // delivered over gRPC stream
    Spooled, // written to disk spool
    Dropped, // spool write also failed — data lost
}

#[derive(Debug)]
pub struct SenderStats {
    pub batches_sent:        u64,
    pub batches_spooled:     u64,
    pub batches_acked:       u64,
    pub send_errors:         u64,
    pub reconnects:          u64,
    pub throttle_ratio:      f32,
    pub spooling:            bool,
    pub spool_pending_bytes: u64,
}

// ── Tests ─────────────────────────────────────────────────────
#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn open_spool(max: u64) -> DiskSpool {
        let dir  = tempdir().unwrap();
        let path = dir.path().join("test.spool");
        // Keep dir alive by leaking (fine in tests)
        std::mem::forget(dir);
        DiskSpool::open(&path, max).unwrap()
    }

    fn make_ack(throttle: f32) -> proto::IngestAck {
        proto::IngestAck {
            accepted: 10,
            rejected: 0,
            retry_after_ms: 0,
            suggested_batch_bytes: 0,
            throttle_ratio: throttle,
        }
    }

    #[test]
    fn spool_append_and_replay() {
        let dir   = tempdir().unwrap();
        let path  = dir.path().join("spool.bin");
        let mut s = DiskSpool::open(&path, 100 * 1024 * 1024).unwrap();

        let batch1 = b"batch one payload";
        let batch2 = b"batch two payload longer";

        s.append(batch1).unwrap();
        s.append(batch2).unwrap();

        // Reset read cursor to beginning for replay
        s.reset_replay();

        let r1 = s.next_entry().unwrap().unwrap();
        let r2 = s.next_entry().unwrap().unwrap();
        assert!(s.next_entry().unwrap().is_none());

        assert_eq!(r1, batch1);
        assert_eq!(r2, batch2);
    }

    #[test]
    fn spool_is_empty_after_full_replay() {
        let dir  = tempdir().unwrap();
        let path = dir.path().join("spool.bin");
        let mut s = DiskSpool::open(&path, 100 * 1024 * 1024).unwrap();

        s.append(b"entry").unwrap();
        s.reset_replay();
        let _ = s.next_entry().unwrap();
        assert!(s.is_empty());
    }

    #[test]
    fn spool_pending_bytes_tracks_correctly() {
        let dir  = tempdir().unwrap();
        let path = dir.path().join("spool.bin");
        let mut s = DiskSpool::open(&path, 100 * 1024 * 1024).unwrap();

        assert_eq!(s.pending_bytes(), 0);
        s.append(b"hello").unwrap(); // 4 + 5 = 9 bytes written
        // read_offset stays at original write_offset until reset_replay
        // pending = write_offset - read_offset = 9 - 0 = 9
        s.reset_replay();
        assert_eq!(s.pending_bytes(), 9);
    }

    #[test]
    fn backpressure_spool_threshold() {
        let mut bp = BackpressureState::default();

        bp.update_from_ack(&make_ack(0.5));
        assert!(!bp.should_spool());

        bp.update_from_ack(&make_ack(0.81));
        assert!(bp.should_spool());

        bp.update_from_ack(&make_ack(0.3));
        assert!(!bp.should_spool());
    }

    #[test]
    fn flush_interval_multiplier_scales() {
        let mut bp = BackpressureState::default();

        bp.update_from_ack(&make_ack(0.0));
        assert!((bp.flush_interval_multiplier() - 1.0).abs() < 0.01);

        bp.update_from_ack(&make_ack(1.0));
        assert!((bp.flush_interval_multiplier() - 4.0).abs() < 0.01);
    }

    #[test]
    fn ack_effect_recovery_when_spool_non_empty() {
        let dir  = tempdir().unwrap();
        let path = dir.path().join("spool.bin");
        let cfg  = SenderConfig {
            spool_path: path.clone(),
            ..Default::default()
        };

        let mut sender = Sender::new(cfg).unwrap();

        // Force into spooling state
        sender.bp.update_from_ack(&make_ack(0.9));
        sender.spool.append(b"pending batch").unwrap();
        sender.spool.reset_replay();

        // Now backend recovers
        let effect = sender.on_ack(make_ack(0.1));
        assert_eq!(effect, AckEffect::RecoveryNeeded);
    }

    #[test]
    fn exponential_backoff_doubles() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("spool.bin");
        let cfg = SenderConfig {
            spool_path: path,
            max_retry_delay: Duration::from_secs(10),
            ..Default::default()
        };
        let mut sender = Sender::new(cfg).unwrap();

        let d1 = sender.next_backoff();
        let d2 = sender.next_backoff();
        let d3 = sender.next_backoff();

        assert_eq!(d1, Duration::from_millis(100));
        assert_eq!(d2, Duration::from_millis(200));
        assert_eq!(d3, Duration::from_millis(400));
    }

    #[test]
    fn backoff_caps_at_max() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("spool.bin");
        let cfg = SenderConfig {
            spool_path: path,
            max_retry_delay: Duration::from_millis(500),
            ..Default::default()
        };
        let mut sender = Sender::new(cfg).unwrap();

        for _ in 0..20 { sender.next_backoff(); }
        let capped = sender.next_backoff();
        assert_eq!(capped, Duration::from_millis(500));
    }
}