[package]
name    = "olopa-common"
version = "0.1.0"
edition = "2021"

# no_std so this crate can be used from both the eBPF crate and the agent
[lib]

[features]
# Enable aya::Pod impls — only when building for the host (agent side)
user = ["dep:aya"]

[dependencies]
aya = { version = "0.13", optional = true }