[package]
name    = "olopa-agent"
version = "0.1.0"
edition = "2021"
build   = "src/build.rs"

[[bin]]
name = "olopa-agent"
path = "src/main.rs"

[dependencies]
aya          = { version = "0.13", features = ["async_tokio"] }
aya-log      = "0.2"
olopa-common = { path = "../common", features = ["user"] }
tokio        = { version = "1", features = ["full"] }
anyhow       = "1"
clap         = { version = "4", features = ["derive"] }
log          = "0.4"
env_logger   = "0.11"
crossbeam-utils = { version = "0.8.21"}
parking_lot = "0.12"

[build-dependencies]
# build.rs compiles the eBPF crate and embeds it into the agent binary
aya-build    = "0.1"
