//! Runtime IR evaluator for userspace rule execution.
//!
//! This module loads the JSON artifact emitted by `oilc --emit-runtime-ir`
//! and evaluates each rule predicate against `IngestEvent`.

use std::collections::HashMap;
use std::fs;
use std::net::{IpAddr, Ipv4Addr, ToSocketAddrs};
use std::path::Path;
use std::sync::{Mutex, OnceLock};
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use log::{debug, log_enabled, Level};
use serde::Deserialize;

use crate::agent::{IngestEvent, RuleMatch};

const DNS_CACHE_TTL: Duration = Duration::from_secs(60);
type DnsCache = HashMap<String, (Instant, Vec<u32>)>;
static DOMAIN_IP_CACHE: OnceLock<Mutex<DnsCache>> = OnceLock::new();
const EPOCH_NS_MIN_2000: u64 = 946_684_800_000_000_000; // 2000-01-01T00:00:00Z

#[derive(Debug, Clone, Copy)]
struct ClockAnchor {
    monotonic_ns: u64,
    realtime_ns: u64,
}

static CLOCK_ANCHOR: OnceLock<Option<ClockAnchor>> = OnceLock::new();

#[derive(Debug, Clone, Deserialize)]
pub struct RuntimeProgram {
    /// Runtime IR schema version. Current supported version: 1.
    pub version: u32,
    /// Flat list of compiled rules.
    pub rules: Vec<RuntimeRule>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RuntimeRule {
    /// Stable rule identifier generated by the compiler.
    pub id: String,
    /// Human-readable rule name.
    pub name: String,
    /// All predicates must evaluate to true for a match.
    pub predicates: Vec<RuntimeExpr>,
    /// Optional response plan; present in enriched runtime-ir output.
    #[serde(default)]
    pub respond: RuntimeRespondPlan,
}

#[derive(Debug, Clone, Deserialize, Default)]
pub struct RuntimeRespondPlan {
    #[serde(default)]
    pub branches: Vec<RuntimeRespondBranch>,
}

#[derive(Debug, Clone, Deserialize, Default)]
pub struct RuntimeRespondBranch {
    #[serde(default)]
    pub actions: Vec<RuntimeAction>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RuntimeAction {
    pub action: String,
    #[serde(default)]
    pub target: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum RuntimeExpr {
    /// Literal boolean.
    Bool { value: bool },
    /// Literal integer.
    Int { value: i64 },
    /// Literal float.
    Float { value: f64 },
    /// Literal string.
    Str { value: String },
    /// Event field path such as `pid` or `event.pid`.
    Field { path: String },
    /// Logical conjunction.
    And {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Logical disjunction.
    Or {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Logical negation.
    Not { expr: Box<RuntimeExpr> },
    /// Equality.
    Eq {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Inequality.
    Ne {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Less than.
    Lt {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Greater than.
    Gt {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Less or equal.
    Le {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Greater or equal.
    Ge {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Membership check.
    In {
        lhs: Box<RuntimeExpr>,
        rhs: Vec<RuntimeExpr>,
    },
    /// String prefix check.
    StartsWith {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// String suffix check.
    EndsWith {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// String contains check.
    Contains {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Placeholder for operators not yet implemented in runtime.
    Unsupported { kind: String },
}

#[derive(Debug, Clone, PartialEq)]
enum Value {
    Bool(bool),
    Number(f64),
    String(String),
    Ip(u32),
    Null,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FieldSemantic {
    Domain,
}

#[derive(Debug, Clone)]
pub struct RuntimeIrRuleEngine {
    /// Loaded, compiler-produced runtime program.
    program: RuntimeProgram,
}

#[derive(Debug, Clone, Deserialize)]
struct RuntimeArtifactMultiUnit {
    version: u32,
    units: Vec<RuntimeArtifactUnit>,
}

#[derive(Debug, Clone, Deserialize)]
struct RuntimeArtifactUnit {
    id: String,
    program: RuntimeProgram,
}

impl RuntimeIrRuleEngine {
    /// Load runtime IR JSON from disk.
    pub fn from_file(path: &Path) -> Result<Self> {
        let content = fs::read_to_string(path)
            .with_context(|| format!("failed to read runtime-ir file: {}", path.display()))?;
        let program = parse_runtime_program(&content).with_context(|| {
            format!(
                "failed to parse runtime-ir JSON (single or multi-unit): {}",
                path.display()
            )
        })?;
        Ok(Self { program })
    }

    /// Evaluate all rules for a single event and return every match.
    pub fn evaluate_matches(&self, event: &IngestEvent) -> Vec<RuleMatch> {
        // Version-gate execution so unknown schemas fail closed.
        if self.program.version != 1 {
            return Vec::new();
        }

        let mut out = Vec::new();
        for rule in &self.program.rules {
            let uses_time_context = rule_uses_time_context(rule);
            let matched = rule.predicates.iter().all(|pred| eval_bool(pred, event));
            if should_debug_time_ir() && uses_time_context {
                debug_time_ir_eval(rule, event, matched);
            }
            if matched {
                out.push(RuleMatch {
                    rule_id: rule.id.clone(),
                    rule_name: rule.name.clone(),
                    enforce_block_egress: rule_has_block_egress(rule),
                });
            }
        }
        out
    }

    pub fn rule_count(&self) -> usize {
        self.program.rules.len()
    }
}

// Accept both:
// - single unit: {version, rules}
// - multi unit:  {version, units:[{id, program:{version, rules}}]}
fn parse_runtime_program(content: &str) -> Result<RuntimeProgram> {
    if let Ok(program) = serde_json::from_str::<RuntimeProgram>(content) {
        return Ok(program);
    }

    let multi: RuntimeArtifactMultiUnit = serde_json::from_str(content)?;
    let mut merged_rules = Vec::new();
    for unit in multi.units {
        // Keep `id` consumed intentionally; useful for future per-unit routing.
        let _unit_id = unit.id;
        merged_rules.extend(unit.program.rules);
    }

    Ok(RuntimeProgram {
        version: multi.version,
        rules: merged_rules,
    })
}

fn rule_has_block_egress(rule: &RuntimeRule) -> bool {
    rule.respond
        .branches
        .iter()
        .flat_map(|b| b.actions.iter())
        .any(|a| a.action == "block_egress")
}

fn should_debug_time_ir() -> bool {
    if !log_enabled!(Level::Debug) {
        return false;
    }
    match std::env::var("OLOPA_DEBUG_TIME_IR") {
        Ok(v) => {
            let flag = v.trim().to_ascii_lowercase();
            matches!(flag.as_str(), "1" | "true" | "yes" | "on")
        }
        Err(_) => false,
    }
}

fn debug_time_ir_eval(rule: &RuntimeRule, event: &IngestEvent, matched: bool) {
    if let Some(tm) = event_local_time(event) {
        debug!(
            "time-ir-check rule={} matched={} ts_ns={} weekday={} hour={} minute={} business_hours={}",
            rule.name,
            matched,
            event.ts_ns,
            weekday_name(tm.tm_wday),
            tm.tm_hour,
            tm.tm_min,
            is_business_hour(&tm)
        );
    } else {
        debug!(
            "time-ir-check rule={} matched={} ts_ns={} localtime=unavailable",
            rule.name, matched, event.ts_ns
        );
    }
}

fn rule_uses_time_context(rule: &RuntimeRule) -> bool {
    rule.predicates.iter().any(expr_uses_time_context)
}

fn expr_uses_time_context(expr: &RuntimeExpr) -> bool {
    match expr {
        RuntimeExpr::Field { path } => {
            path == "time"
                || path.starts_with("time.")
                || matches!(
                    path.rsplit('.').next().unwrap_or(path.as_str()),
                    "weekday"
                        | "day_of_week"
                        | "hour"
                        | "minute"
                        | "is_business_hour"
                        | "business_hours"
                )
        }
        RuntimeExpr::And { lhs, rhs }
        | RuntimeExpr::Or { lhs, rhs }
        | RuntimeExpr::Eq { lhs, rhs }
        | RuntimeExpr::Ne { lhs, rhs }
        | RuntimeExpr::Lt { lhs, rhs }
        | RuntimeExpr::Gt { lhs, rhs }
        | RuntimeExpr::Le { lhs, rhs }
        | RuntimeExpr::Ge { lhs, rhs }
        | RuntimeExpr::StartsWith { lhs, rhs }
        | RuntimeExpr::EndsWith { lhs, rhs }
        | RuntimeExpr::Contains { lhs, rhs } => {
            expr_uses_time_context(lhs) || expr_uses_time_context(rhs)
        }
        RuntimeExpr::In { lhs, rhs } => {
            expr_uses_time_context(lhs) || rhs.iter().any(expr_uses_time_context)
        }
        RuntimeExpr::Not { expr } => expr_uses_time_context(expr),
        RuntimeExpr::Bool { .. }
        | RuntimeExpr::Int { .. }
        | RuntimeExpr::Float { .. }
        | RuntimeExpr::Str { .. }
        | RuntimeExpr::Unsupported { .. } => false,
    }
}

// Evaluate expression in boolean context.
fn eval_bool(expr: &RuntimeExpr, event: &IngestEvent) -> bool {
    match expr {
        RuntimeExpr::Bool { value } => *value,
        RuntimeExpr::And { lhs, rhs } => eval_bool(lhs, event) && eval_bool(rhs, event),
        RuntimeExpr::Or { lhs, rhs } => eval_bool(lhs, event) || eval_bool(rhs, event),
        RuntimeExpr::Not { expr } => !eval_bool(expr, event),
        RuntimeExpr::Eq { lhs, rhs } => eval_eq(lhs, rhs, event),
        RuntimeExpr::Ne { lhs, rhs } => !eval_eq(lhs, rhs, event),
        RuntimeExpr::Lt { lhs, rhs } => compare_ord(lhs, rhs, event, |a, b| a < b),
        RuntimeExpr::Gt { lhs, rhs } => compare_ord(lhs, rhs, event, |a, b| a > b),
        RuntimeExpr::Le { lhs, rhs } => compare_ord(lhs, rhs, event, |a, b| a <= b),
        RuntimeExpr::Ge { lhs, rhs } => compare_ord(lhs, rhs, event, |a, b| a >= b),
        RuntimeExpr::In { lhs, rhs } => eval_in(lhs, rhs, event),
        RuntimeExpr::StartsWith { lhs, rhs } => {
            to_string(eval_value(lhs, event)).starts_with(&to_string(eval_value(rhs, event)))
        }
        RuntimeExpr::EndsWith { lhs, rhs } => {
            to_string(eval_value(lhs, event)).ends_with(&to_string(eval_value(rhs, event)))
        }
        RuntimeExpr::Contains { lhs, rhs } => {
            to_string(eval_value(lhs, event)).contains(&to_string(eval_value(rhs, event)))
        }
        RuntimeExpr::Unsupported { .. } => false,
        _ => false,
    }
}

fn eval_eq(lhs: &RuntimeExpr, rhs: &RuntimeExpr, event: &IngestEvent) -> bool {
    let lhs_value = eval_value(lhs, event);
    let rhs_value = eval_value(rhs, event);
    values_equal(lhs, &lhs_value, rhs, &rhs_value)
}

fn eval_in(lhs: &RuntimeExpr, rhs: &[RuntimeExpr], event: &IngestEvent) -> bool {
    let lhs_value = eval_value(lhs, event);
    rhs.iter().any(|item| {
        let rhs_value = eval_value(item, event);
        values_equal(lhs, &lhs_value, item, &rhs_value)
    })
}

fn field_path(expr: &RuntimeExpr) -> Option<&str> {
    match expr {
        RuntimeExpr::Field { path } => Some(path.as_str()),
        _ => None,
    }
}

fn is_domain_path(path: &str) -> bool {
    path == "domain" || path.ends_with(".domain")
}

fn field_semantic(expr: &RuntimeExpr) -> Option<FieldSemantic> {
    let path = field_path(expr)?;
    if is_domain_path(path) {
        return Some(FieldSemantic::Domain);
    }
    None
}

// Core value equality with semantic adapters.
// This keeps operators generic and lets `==` / `in` share identical behavior.
fn values_equal(lhs_expr: &RuntimeExpr, lhs: &Value, rhs_expr: &RuntimeExpr, rhs: &Value) -> bool {
    if let Some(result) = semantic_eq(lhs_expr, lhs, rhs_expr, rhs) {
        return result;
    }

    match (value_as_ipv4(lhs), value_as_ipv4(rhs)) {
        (Some(a), Some(b)) => a == b,
        _ => lhs == rhs,
    }
}

fn semantic_eq(
    lhs_expr: &RuntimeExpr,
    lhs: &Value,
    rhs_expr: &RuntimeExpr,
    rhs: &Value,
) -> Option<bool> {
    if matches!(field_semantic(lhs_expr), Some(FieldSemantic::Domain)) {
        if let Value::String(domain) = rhs {
            return Some(
                value_as_ipv4(lhs)
                    .map(|ip| domain_matches_ip(domain, ip))
                    .unwrap_or(false),
            );
        }
    }
    if matches!(field_semantic(rhs_expr), Some(FieldSemantic::Domain)) {
        if let Value::String(domain) = lhs {
            return Some(
                value_as_ipv4(rhs)
                    .map(|ip| domain_matches_ip(domain, ip))
                    .unwrap_or(false),
            );
        }
    }
    None
}

fn value_as_ipv4(value: &Value) -> Option<u32> {
    match value {
        Value::Ip(ip) => Some(*ip),
        Value::String(s) => s.parse::<Ipv4Addr>().ok().map(u32::from),
        _ => None,
    }
}

fn domain_matches_ip(domain: &str, ip: u32) -> bool {
    resolve_domain_ipv4_cached(domain)
        .into_iter()
        .any(|resolved| resolved == ip)
}

fn resolve_domain_ipv4_cached(domain: &str) -> Vec<u32> {
    let cache = DOMAIN_IP_CACHE.get_or_init(|| Mutex::new(HashMap::new()));
    let now = Instant::now();

    if let Ok(guard) = cache.lock() {
        if let Some((fetched_at, ips)) = guard.get(domain) {
            if now.duration_since(*fetched_at) <= DNS_CACHE_TTL {
                return ips.clone();
            }
        }
    }

    let mut resolved = Vec::new();
    if let Ok(addrs) = (domain, 0u16).to_socket_addrs() {
        for addr in addrs {
            if let IpAddr::V4(v4) = addr.ip() {
                let ip = u32::from(v4);
                if !resolved.contains(&ip) {
                    resolved.push(ip);
                }
            }
        }
    }

    if let Ok(mut guard) = cache.lock() {
        guard.insert(domain.to_string(), (Instant::now(), resolved.clone()));
    }

    resolved
}

// Compare two expressions after numeric coercion.
fn compare_ord(
    lhs: &RuntimeExpr,
    rhs: &RuntimeExpr,
    event: &IngestEvent,
    cmp: impl Fn(f64, f64) -> bool,
) -> bool {
    match (
        to_number(eval_value(lhs, event)),
        to_number(eval_value(rhs, event)),
    ) {
        (Some(a), Some(b)) => cmp(a, b),
        _ => false,
    }
}

// Evaluate expression in value context (bool/number/string/null).
fn eval_value(expr: &RuntimeExpr, event: &IngestEvent) -> Value {
    match expr {
        RuntimeExpr::Bool { value } => Value::Bool(*value),
        RuntimeExpr::Int { value } => Value::Number(*value as f64),
        RuntimeExpr::Float { value } => Value::Number(*value),
        RuntimeExpr::Str { value } => Value::String(value.clone()),
        RuntimeExpr::Field { path } => lookup_field(path, event),
        RuntimeExpr::Eq { .. }
        | RuntimeExpr::Ne { .. }
        | RuntimeExpr::Lt { .. }
        | RuntimeExpr::Gt { .. }
        | RuntimeExpr::Le { .. }
        | RuntimeExpr::Ge { .. }
        | RuntimeExpr::In { .. }
        | RuntimeExpr::StartsWith { .. }
        | RuntimeExpr::EndsWith { .. }
        | RuntimeExpr::Contains { .. }
        | RuntimeExpr::And { .. }
        | RuntimeExpr::Or { .. }
        | RuntimeExpr::Not { .. } => Value::Bool(eval_bool(expr, event)),
        RuntimeExpr::Unsupported { .. } => Value::Null,
    }
}

// Resolve known event field names into runtime values.
fn lookup_field(path: &str, event: &IngestEvent) -> Value {
    let key = path.rsplit('.').next().unwrap_or(path);
    match key {
        "ts_ns" => Value::Number(event.ts_ns as f64),
        "weekday" | "day_of_week" => event_local_time(event)
            .map(|t| Value::String(weekday_name(t.tm_wday).to_string()))
            .unwrap_or(Value::Null),
        "hour" => event_local_time(event)
            .map(|t| Value::Number(t.tm_hour as f64))
            .unwrap_or(Value::Null),
        "minute" => event_local_time(event)
            .map(|t| Value::Number(t.tm_min as f64))
            .unwrap_or(Value::Null),
        "is_business_hour" | "business_hours" => event_local_time(event)
            .map(|t| Value::Bool(is_business_hour(&t)))
            .unwrap_or(Value::Bool(false)),
        "pid" => Value::Number(event.pid as f64),
        "process_id" => Value::Number(event.pid as f64),
        "uid" => Value::Number(event.uid as f64),
        "event_type" => Value::Number(event.event_type as f64),
        "vertex_id" => Value::Number(event.vertex_id as f64),
        "dst_vertex_id" => Value::Number(event.dst_vertex_id as f64),
        // `p.name` in OIL maps to kernel `comm` in this userspace event model.
        "name" | "comm" => Value::String(event_comm(event)),
        "direction" if event.event_type == 3 => Value::String("outbound".to_string()),
        // Domain fields are represented as observed destination IPv4 on wire.
        // Semantic equality handles domain-string resolution when compared.
        "domain" if event.event_type == 3 && event.net_dst_ip != 0 => Value::Ip(event.net_dst_ip),
        "dst_ip" | "ip" if event.event_type == 3 && event.net_dst_ip != 0 => {
            Value::Ip(event.net_dst_ip)
        }
        "dst_port" | "port" if event.event_type == 3 => Value::Number(event.net_dst_port as f64),
        "comm_id" => Value::Number(event.comm_id as f64),
        "risk_score" | "score" => Value::Number(event.risk_score as f64),
        _ => Value::Null,
    }
}

// Convert Value into number if possible.
fn to_number(value: Value) -> Option<f64> {
    match value {
        Value::Number(v) => Some(v),
        Value::Bool(v) => Some(if v { 1.0 } else { 0.0 }),
        Value::String(v) => v.parse::<f64>().ok(),
        Value::Ip(v) => Some(v as f64),
        Value::Null => None,
    }
}

// Convert Value into string for string operations.
fn to_string(value: Value) -> String {
    match value {
        Value::String(v) => v,
        Value::Ip(v) => Ipv4Addr::from(v).to_string(),
        Value::Number(v) => v.to_string(),
        Value::Bool(v) => {
            if v {
                "true".to_string()
            } else {
                "false".to_string()
            }
        }
        Value::Null => String::new(),
    }
}

fn event_comm(event: &IngestEvent) -> String {
    let end = event
        .comm
        .iter()
        .position(|&b| b == 0)
        .unwrap_or(event.comm.len());
    String::from_utf8_lossy(&event.comm[..end]).to_string()
}

fn event_local_time(event: &IngestEvent) -> Option<libc::tm> {
    let realtime_ns = event_realtime_ns(event.ts_ns)?;
    let secs = realtime_ns / 1_000_000_000;
    let mut epoch: libc::time_t = secs.try_into().ok()?;
    let mut tm = std::mem::MaybeUninit::<libc::tm>::uninit();
    // SAFETY: localtime_r initializes `tm` when non-null pointer is returned.
    let ok = unsafe { libc::localtime_r(&mut epoch, tm.as_mut_ptr()) };
    if ok.is_null() {
        None
    } else {
        // SAFETY: `localtime_r` returned non-null and populated `tm`.
        Some(unsafe { tm.assume_init() })
    }
}

// Kernel probes emit `bpf_ktime_get_ns()` (monotonic since boot).
// Convert that to wall-clock nanoseconds using a startup anchor so
// weekday/hour rules evaluate against real local time.
fn event_realtime_ns(ts_ns: u64) -> Option<u64> {
    // If we already have epoch-like ns (e.g. tests or future probe change),
    // use it directly.
    if ts_ns >= EPOCH_NS_MIN_2000 {
        return Some(ts_ns);
    }

    let anchor = CLOCK_ANCHOR
        .get_or_init(capture_clock_anchor)
        .as_ref()
        .copied()?;
    let delta = ts_ns as i128 - anchor.monotonic_ns as i128;
    let realtime = anchor.realtime_ns as i128 + delta;
    if realtime <= 0 {
        None
    } else {
        Some(realtime as u64)
    }
}

fn capture_clock_anchor() -> Option<ClockAnchor> {
    Some(ClockAnchor {
        monotonic_ns: read_clock_ns(libc::CLOCK_MONOTONIC)?,
        realtime_ns: read_clock_ns(libc::CLOCK_REALTIME)?,
    })
}

fn read_clock_ns(clock_id: libc::clockid_t) -> Option<u64> {
    let mut ts = libc::timespec {
        tv_sec: 0,
        tv_nsec: 0,
    };
    // SAFETY: `clock_gettime` writes to provided valid pointer.
    let rc = unsafe { libc::clock_gettime(clock_id, &mut ts) };
    if rc != 0 || ts.tv_sec < 0 || ts.tv_nsec < 0 {
        return None;
    }
    let sec_ns = (ts.tv_sec as u128).saturating_mul(1_000_000_000);
    let ns = sec_ns.saturating_add(ts.tv_nsec as u128);
    u64::try_from(ns).ok()
}

fn weekday_name(wday: libc::c_int) -> &'static str {
    match wday {
        0 => "sunday",
        1 => "monday",
        2 => "tuesday",
        3 => "wednesday",
        4 => "thursday",
        5 => "friday",
        6 => "saturday",
        _ => "unknown",
    }
}

fn is_business_hour(tm: &libc::tm) -> bool {
    // Monday-Friday + 09:00..16:59 local time.
    (1..=5).contains(&tm.tm_wday) && (9..17).contains(&tm.tm_hour)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use std::process::Command;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_runtime_ir_path() -> PathBuf {
        let ts = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time")
            .as_nanos();
        std::env::temp_dir().join(format!("olopa_runtime_ir_test_{ts}.json"))
    }

    fn temp_runtime_ir_dir() -> PathBuf {
        let ts = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time")
            .as_nanos();
        std::env::temp_dir().join(format!("olopa_runtime_ir_dir_{ts}"))
    }

    #[test]
    fn evaluates_numeric_rule() {
        let engine = RuntimeIrRuleEngine {
            program: RuntimeProgram {
                version: 1,
                rules: vec![RuntimeRule {
                    id: "r1".to_string(),
                    name: "r1".to_string(),
                    predicates: vec![RuntimeExpr::Eq {
                        lhs: Box::new(RuntimeExpr::Field {
                            path: "pid".to_string(),
                        }),
                        rhs: Box::new(RuntimeExpr::Int { value: 42 }),
                    }],
                    respond: RuntimeRespondPlan::default(),
                }],
            },
        };

        let event = IngestEvent {
            ts_ns: 0,
            pid: 42,
            uid: 0,
            event_type: 1,
            vertex_id: 42,
            dst_vertex_id: 0,
            net_dst_ip: 0,
            net_dst_port: 0,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.1,
        };
        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_id, "r1");
        assert!(!matches[0].enforce_block_egress);
    }

    #[test]
    fn detects_time_context_usage_in_rule_predicates() {
        let rule = RuntimeRule {
            id: "r1".to_string(),
            name: "time_rule".to_string(),
            predicates: vec![RuntimeExpr::And {
                lhs: Box::new(RuntimeExpr::Eq {
                    lhs: Box::new(RuntimeExpr::Field {
                        path: "time.weekday".to_string(),
                    }),
                    rhs: Box::new(RuntimeExpr::Str {
                        value: "monday".to_string(),
                    }),
                }),
                rhs: Box::new(RuntimeExpr::Ge {
                    lhs: Box::new(RuntimeExpr::Field {
                        path: "time.hour".to_string(),
                    }),
                    rhs: Box::new(RuntimeExpr::Int { value: 9 }),
                }),
            }],
            respond: RuntimeRespondPlan::default(),
        };
        assert!(rule_uses_time_context(&rule));
    }

    #[test]
    fn does_not_flag_non_time_predicates_as_time_context() {
        let rule = RuntimeRule {
            id: "r1".to_string(),
            name: "pid_rule".to_string(),
            predicates: vec![RuntimeExpr::Eq {
                lhs: Box::new(RuntimeExpr::Field {
                    path: "p.pid".to_string(),
                }),
                rhs: Box::new(RuntimeExpr::Int { value: 42 }),
            }],
            respond: RuntimeRespondPlan::default(),
        };
        assert!(!rule_uses_time_context(&rule));
    }

    #[test]
    fn loads_oilc_runtime_ir_json_file_and_matches_rule() {
        let path = temp_runtime_ir_path();
        let json = r#"{
  "version": 1,
  "rules": [
    {
      "id": "rule:0:pid_42",
      "name": "pid_42",
      "predicates": [
        {
          "op": "eq",
          "lhs": { "op": "field", "path": "pid" },
          "rhs": { "op": "int", "value": 42 }
        }
      ]
    }
  ]
}"#;
        fs::write(&path, json).expect("write runtime ir json");

        let engine = RuntimeIrRuleEngine::from_file(&path).expect("load runtime ir");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 42,
            uid: 0,
            event_type: 1,
            vertex_id: 42,
            dst_vertex_id: 0,
            net_dst_ip: 0,
            net_dst_port: 0,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.1,
        };

        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_id, "rule:0:pid_42");
        assert_eq!(matches[0].rule_name, "pid_42");
        assert!(!matches[0].enforce_block_egress);

        let _ = fs::remove_file(path);
    }

    #[test]
    fn loads_multi_unit_runtime_ir_and_merges_rules() {
        let path = temp_runtime_ir_path();
        let json = r#"{
  "version": 1,
  "units": [
    {
      "id": "unit-a",
      "program": {
        "version": 1,
        "rules": [
          {
            "id": "rule:pid_42",
            "name": "pid_42",
            "predicates": [
              {
                "op": "eq",
                "lhs": { "op": "field", "path": "pid" },
                "rhs": { "op": "int", "value": 42 }
              }
            ]
          }
        ]
      }
    },
    {
      "id": "unit-b",
      "program": {
        "version": 1,
        "rules": [
          {
            "id": "rule:uid_7",
            "name": "uid_7",
            "predicates": [
              {
                "op": "eq",
                "lhs": { "op": "field", "path": "uid" },
                "rhs": { "op": "int", "value": 7 }
              }
            ]
          }
        ]
      }
    }
  ]
}"#;
        fs::write(&path, json).expect("write runtime ir json");

        let engine = RuntimeIrRuleEngine::from_file(&path).expect("load runtime ir");
        assert_eq!(engine.rule_count(), 2);

        let event = IngestEvent {
            ts_ns: 0,
            pid: 42,
            uid: 7,
            event_type: 1,
            vertex_id: 0,
            dst_vertex_id: 0,
            net_dst_ip: 0,
            net_dst_port: 0,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.0,
        };
        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 2);
        assert_eq!(matches[0].rule_id, "rule:pid_42");
        assert_eq!(matches[1].rule_id, "rule:uid_7");
        assert!(!matches[0].enforce_block_egress);
        assert!(!matches[1].enforce_block_egress);

        let _ = fs::remove_file(path);
    }

    #[test]
    fn loads_runtime_ir_emitted_by_oilc_cli_and_matches() {
        let dir = temp_runtime_ir_dir();
        fs::create_dir_all(&dir).expect("create temp dir");

        let source_path = dir.join("rule.oil");
        let runtime_ir_path = dir.join("runtime-ir.json");
        let src = r#"
rule "pid_42" {
  from endpoint.process
  correlate process.spawn as p
  where p.pid == 42
  respond alert high
}
"#;
        fs::write(&source_path, src).expect("write oil source");

        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let repo_root = manifest_dir
            .parent()
            .and_then(|p| p.parent())
            .expect("repo root");
        let oilc_manifest = repo_root.join("oilc").join("Cargo.toml");

        let output = Command::new("cargo")
            .arg("run")
            .arg("--manifest-path")
            .arg(&oilc_manifest)
            .arg("--")
            .arg("--source")
            .arg(&source_path)
            .arg("--emit-runtime-ir")
            .arg(&runtime_ir_path)
            .arg("--mode")
            .arg("check")
            .current_dir(repo_root)
            .output()
            .expect("run oilc cli");
        assert!(
            output.status.success(),
            "oilc cli failed:\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );

        let engine = RuntimeIrRuleEngine::from_file(&runtime_ir_path).expect("load runtime ir");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 42,
            uid: 0,
            event_type: 1,
            vertex_id: 0,
            dst_vertex_id: 0,
            net_dst_ip: 0,
            net_dst_port: 0,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.0,
        };
        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_name, "pid_42");
        assert!(!matches[0].enforce_block_egress);

        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn loads_multi_source_runtime_ir_emitted_by_oilc_cli_and_matches_both_rules() {
        let dir = temp_runtime_ir_dir();
        fs::create_dir_all(&dir).expect("create temp dir");

        let source_a = dir.join("rule_a.oil");
        let source_b = dir.join("rule_b.oil");
        let runtime_ir_path = dir.join("runtime-ir.json");

        let src_a = r#"
rule "pid_42" {
  from endpoint.process
  correlate process.spawn as p
  where p.pid == 42
  respond alert high
}
"#;
        let src_b = r#"
rule "uid_7" {
  from endpoint.process
  correlate process.spawn as p
  where p.uid == 7
  respond alert medium
}
"#;
        fs::write(&source_a, src_a).expect("write source a");
        fs::write(&source_b, src_b).expect("write source b");

        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let repo_root = manifest_dir
            .parent()
            .and_then(|p| p.parent())
            .expect("repo root");
        let oilc_manifest = repo_root.join("oilc").join("Cargo.toml");

        let output = Command::new("cargo")
            .arg("run")
            .arg("--manifest-path")
            .arg(&oilc_manifest)
            .arg("--")
            .arg("--source")
            .arg(&source_a)
            .arg("--source")
            .arg(&source_b)
            .arg("--emit-runtime-ir")
            .arg(&runtime_ir_path)
            .arg("--mode")
            .arg("check")
            .current_dir(repo_root)
            .output()
            .expect("run oilc cli");
        assert!(
            output.status.success(),
            "oilc cli failed:\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );

        let engine = RuntimeIrRuleEngine::from_file(&runtime_ir_path).expect("load runtime ir");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 42,
            uid: 7,
            event_type: 1,
            vertex_id: 0,
            dst_vertex_id: 0,
            net_dst_ip: 0,
            net_dst_port: 0,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.0,
        };
        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 2);
        assert!(matches.iter().any(|m| m.rule_name == "pid_42"));
        assert!(matches.iter().any(|m| m.rule_name == "uid_7"));
        assert!(!matches.iter().any(|m| m.enforce_block_egress));

        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn marks_block_egress_rules_for_enforcement() {
        let path = temp_runtime_ir_path();
        let json = r#"{
  "version": 1,
  "rules": [
    {
      "id": "rule:0:block_egress",
      "name": "block_egress",
      "predicates": [
        {
          "op": "eq",
          "lhs": { "op": "field", "path": "pid" },
          "rhs": { "op": "int", "value": 42 }
        }
      ],
      "respond": {
        "branches": [
          {
            "condition": null,
            "actions": [
              { "action": "alert", "severity": "critical" },
              { "action": "block_egress", "target": "n.dest.domain" }
            ]
          }
        ]
      }
    }
  ]
}"#;
        fs::write(&path, json).expect("write runtime ir json");

        let engine = RuntimeIrRuleEngine::from_file(&path).expect("load runtime ir");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 42,
            uid: 0,
            event_type: 3,
            vertex_id: 42,
            dst_vertex_id: 0,
            net_dst_ip: u32::from(Ipv4Addr::LOCALHOST),
            net_dst_port: 443,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.1,
        };

        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_name, "block_egress");
        assert!(matches[0].enforce_block_egress);

        let _ = fs::remove_file(path);
    }

    #[test]
    fn matches_domain_predicate_against_net_destination_ip() {
        let path = temp_runtime_ir_path();
        let json = r#"{
  "version": 1,
  "rules": [
    {
      "id": "rule:0:localhost_domain",
      "name": "localhost_domain",
      "predicates": [
        {
          "op": "eq",
          "lhs": { "op": "field", "path": "n.dest.domain" },
          "rhs": { "op": "str", "value": "localhost" }
        }
      ]
    }
  ]
}"#;
        fs::write(&path, json).expect("write runtime ir json");

        let engine = RuntimeIrRuleEngine::from_file(&path).expect("load runtime ir");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 9001,
            uid: 0,
            event_type: 3,
            vertex_id: 9001,
            dst_vertex_id: 0,
            net_dst_ip: u32::from(Ipv4Addr::LOCALHOST),
            net_dst_port: 443,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.2,
        };

        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_name, "localhost_domain");

        let _ = fs::remove_file(path);
    }

    #[test]
    fn matches_domain_membership_predicate_against_net_destination_ip() {
        let path = temp_runtime_ir_path();
        let json = r#"{
  "version": 1,
  "rules": [
    {
      "id": "rule:0:localhost_domain_in_list",
      "name": "localhost_domain_in_list",
      "predicates": [
        {
          "op": "in",
          "lhs": { "op": "field", "path": "n.dest.domain" },
          "rhs": [
            { "op": "str", "value": "example.com" },
            { "op": "str", "value": "localhost" }
          ]
        }
      ]
    }
  ]
}"#;
        fs::write(&path, json).expect("write runtime ir json");

        let engine = RuntimeIrRuleEngine::from_file(&path).expect("load runtime ir");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 9002,
            uid: 0,
            event_type: 3,
            vertex_id: 9002,
            dst_vertex_id: 0,
            net_dst_ip: u32::from(Ipv4Addr::LOCALHOST),
            net_dst_port: 443,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.2,
        };

        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_name, "localhost_domain_in_list");

        let _ = fs::remove_file(path);
    }

    #[test]
    fn matches_ip_membership_predicate_against_net_destination_ip() {
        let path = temp_runtime_ir_path();
        let json = r#"{
  "version": 1,
  "rules": [
    {
      "id": "rule:0:loopback_ip_in_list",
      "name": "loopback_ip_in_list",
      "predicates": [
        {
          "op": "in",
          "lhs": { "op": "field", "path": "n.dest.ip" },
          "rhs": [
            { "op": "str", "value": "10.10.10.10" },
            { "op": "str", "value": "127.0.0.1" }
          ]
        }
      ]
    }
  ]
}"#;
        fs::write(&path, json).expect("write runtime ir json");

        let engine = RuntimeIrRuleEngine::from_file(&path).expect("load runtime ir");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 9003,
            uid: 0,
            event_type: 3,
            vertex_id: 9003,
            dst_vertex_id: 0,
            net_dst_ip: u32::from(Ipv4Addr::LOCALHOST),
            net_dst_port: 443,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.2,
        };

        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_name, "loopback_ip_in_list");

        let _ = fs::remove_file(path);
    }

    #[test]
    fn matches_process_name_membership_predicate() {
        let path = temp_runtime_ir_path();
        let json = r#"{
  "version": 1,
  "rules": [
    {
      "id": "rule:0:process_name_in_list",
      "name": "process_name_in_list",
      "predicates": [
        {
          "op": "in",
          "lhs": { "op": "field", "path": "p.name" },
          "rhs": [
            { "op": "str", "value": "bash" },
            { "op": "str", "value": "sh" }
          ]
        }
      ]
    }
  ]
}"#;
        fs::write(&path, json).expect("write runtime ir json");

        let engine = RuntimeIrRuleEngine::from_file(&path).expect("load runtime ir");
        let mut comm = [0u8; 16];
        comm[..4].copy_from_slice(b"bash");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 1337,
            uid: 0,
            event_type: 1,
            vertex_id: 1337,
            dst_vertex_id: 0,
            net_dst_ip: 0,
            net_dst_port: 0,
            comm,
            comm_id: 0,
            risk_score: 0.2,
        };

        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_name, "process_name_in_list");

        let _ = fs::remove_file(path);
    }

    #[test]
    fn evaluates_time_context_fields() {
        let path = temp_runtime_ir_path();
        let mut comm = [0u8; 16];
        comm[..4].copy_from_slice(b"bash");
        let event = IngestEvent {
            ts_ns: 1_704_067_200_000_000_000, // 2024-01-08T12:00:00Z
            pid: 4242,
            uid: 0,
            event_type: 1,
            vertex_id: 4242,
            dst_vertex_id: 0,
            net_dst_ip: 0,
            net_dst_port: 0,
            comm,
            comm_id: 0,
            risk_score: 0.1,
        };

        let local = event_local_time(&event).expect("local time conversion");
        let weekday = weekday_name(local.tm_wday);
        let hour = local.tm_hour as i64;
        let business = is_business_hour(&local);

        let json = format!(
            r#"{{
  "version": 1,
  "rules": [
    {{
      "id": "rule:0:time_context",
      "name": "time_context",
      "predicates": [
        {{
          "op": "and",
          "lhs": {{
            "op": "eq",
            "lhs": {{ "op": "field", "path": "time.weekday" }},
            "rhs": {{ "op": "str", "value": "{weekday}" }}
          }},
          "rhs": {{
            "op": "and",
            "lhs": {{
              "op": "eq",
              "lhs": {{ "op": "field", "path": "time.hour" }},
              "rhs": {{ "op": "int", "value": {hour} }}
            }},
            "rhs": {{
              "op": "eq",
              "lhs": {{ "op": "field", "path": "time.is_business_hour" }},
              "rhs": {{ "op": "bool", "value": {business} }}
            }}
          }}
        }}
      ]
    }}
  ]
}}"#
        );
        fs::write(&path, json).expect("write runtime ir json");

        let engine = RuntimeIrRuleEngine::from_file(&path).expect("load runtime ir");
        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_name, "time_context");

        let _ = fs::remove_file(path);
    }

    #[test]
    fn recognizes_epoch_like_nanoseconds_directly() {
        let ts_ns = 1_704_067_200_000_000_000u64; // 2024-01-08T12:00:00Z
        assert_eq!(event_realtime_ns(ts_ns), Some(ts_ns));
    }
}
