//! Runtime IR evaluator for userspace rule execution.
//!
//! This module loads the JSON artifact emitted by `oilc --emit-runtime-ir`
//! and evaluates each rule predicate against `IngestEvent`.

use std::collections::HashMap;
use std::fs;
use std::net::{IpAddr, Ipv4Addr, ToSocketAddrs};
use std::path::Path;
use std::sync::{Mutex, OnceLock};
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use serde::Deserialize;

use crate::agent::{IngestEvent, RuleMatch};

const DNS_CACHE_TTL: Duration = Duration::from_secs(60);
type DnsCache = HashMap<String, (Instant, Vec<u32>)>;
static DOMAIN_IP_CACHE: OnceLock<Mutex<DnsCache>> = OnceLock::new();

#[derive(Debug, Clone, Deserialize)]
pub struct RuntimeProgram {
    /// Runtime IR schema version. Current supported version: 1.
    pub version: u32,
    /// Flat list of compiled rules.
    pub rules: Vec<RuntimeRule>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RuntimeRule {
    /// Stable rule identifier generated by the compiler.
    pub id: String,
    /// Human-readable rule name.
    pub name: String,
    /// All predicates must evaluate to true for a match.
    pub predicates: Vec<RuntimeExpr>,
    /// Optional response plan; present in enriched runtime-ir output.
    #[serde(default)]
    pub respond: RuntimeRespondPlan,
}

#[derive(Debug, Clone, Deserialize, Default)]
pub struct RuntimeRespondPlan {
    #[serde(default)]
    pub branches: Vec<RuntimeRespondBranch>,
}

#[derive(Debug, Clone, Deserialize, Default)]
pub struct RuntimeRespondBranch {
    #[serde(default)]
    pub actions: Vec<RuntimeAction>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RuntimeAction {
    pub action: String,
    #[serde(default)]
    pub target: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum RuntimeExpr {
    /// Literal boolean.
    Bool { value: bool },
    /// Literal integer.
    Int { value: i64 },
    /// Literal float.
    Float { value: f64 },
    /// Literal string.
    Str { value: String },
    /// Event field path such as `pid` or `event.pid`.
    Field { path: String },
    /// Logical conjunction.
    And {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Logical disjunction.
    Or {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Logical negation.
    Not { expr: Box<RuntimeExpr> },
    /// Equality.
    Eq {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Inequality.
    Ne {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Less than.
    Lt {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Greater than.
    Gt {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Less or equal.
    Le {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Greater or equal.
    Ge {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Membership check.
    In {
        lhs: Box<RuntimeExpr>,
        rhs: Vec<RuntimeExpr>,
    },
    /// String prefix check.
    StartsWith {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// String suffix check.
    EndsWith {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// String contains check.
    Contains {
        lhs: Box<RuntimeExpr>,
        rhs: Box<RuntimeExpr>,
    },
    /// Placeholder for operators not yet implemented in runtime.
    Unsupported { kind: String },
}

#[derive(Debug, Clone, PartialEq)]
enum Value {
    Bool(bool),
    Number(f64),
    String(String),
    Null,
}

#[derive(Debug, Clone)]
pub struct RuntimeIrRuleEngine {
    /// Loaded, compiler-produced runtime program.
    program: RuntimeProgram,
}

#[derive(Debug, Clone, Deserialize)]
struct RuntimeArtifactMultiUnit {
    version: u32,
    units: Vec<RuntimeArtifactUnit>,
}

#[derive(Debug, Clone, Deserialize)]
struct RuntimeArtifactUnit {
    id: String,
    program: RuntimeProgram,
}

impl RuntimeIrRuleEngine {
    /// Load runtime IR JSON from disk.
    pub fn from_file(path: &Path) -> Result<Self> {
        let content = fs::read_to_string(path)
            .with_context(|| format!("failed to read runtime-ir file: {}", path.display()))?;
        let program = parse_runtime_program(&content).with_context(|| {
            format!(
                "failed to parse runtime-ir JSON (single or multi-unit): {}",
                path.display()
            )
        })?;
        Ok(Self { program })
    }

    /// Evaluate all rules for a single event and return every match.
    pub fn evaluate_matches(&self, event: &IngestEvent) -> Vec<RuleMatch> {
        // Version-gate execution so unknown schemas fail closed.
        if self.program.version != 1 {
            return Vec::new();
        }

        let mut out = Vec::new();
        for rule in &self.program.rules {
            if rule.predicates.iter().all(|pred| eval_bool(pred, event)) {
                out.push(RuleMatch {
                    rule_id: rule.id.clone(),
                    rule_name: rule.name.clone(),
                    enforce_block_egress: rule_has_block_egress(rule),
                });
            }
        }
        out
    }

    pub fn rule_count(&self) -> usize {
        self.program.rules.len()
    }
}

// Accept both:
// - single unit: {version, rules}
// - multi unit:  {version, units:[{id, program:{version, rules}}]}
fn parse_runtime_program(content: &str) -> Result<RuntimeProgram> {
    if let Ok(program) = serde_json::from_str::<RuntimeProgram>(content) {
        return Ok(program);
    }

    let multi: RuntimeArtifactMultiUnit = serde_json::from_str(content)?;
    let mut merged_rules = Vec::new();
    for unit in multi.units {
        // Keep `id` consumed intentionally; useful for future per-unit routing.
        let _unit_id = unit.id;
        merged_rules.extend(unit.program.rules);
    }

    Ok(RuntimeProgram {
        version: multi.version,
        rules: merged_rules,
    })
}

fn rule_has_block_egress(rule: &RuntimeRule) -> bool {
    rule.respond
        .branches
        .iter()
        .flat_map(|b| b.actions.iter())
        .any(|a| a.action == "block_egress")
}

// Evaluate expression in boolean context.
fn eval_bool(expr: &RuntimeExpr, event: &IngestEvent) -> bool {
    match expr {
        RuntimeExpr::Bool { value } => *value,
        RuntimeExpr::And { lhs, rhs } => eval_bool(lhs, event) && eval_bool(rhs, event),
        RuntimeExpr::Or { lhs, rhs } => eval_bool(lhs, event) || eval_bool(rhs, event),
        RuntimeExpr::Not { expr } => !eval_bool(expr, event),
        RuntimeExpr::Eq { lhs, rhs } => eval_eq(lhs, rhs, event),
        RuntimeExpr::Ne { lhs, rhs } => !eval_eq(lhs, rhs, event),
        RuntimeExpr::Lt { lhs, rhs } => compare_ord(lhs, rhs, event, |a, b| a < b),
        RuntimeExpr::Gt { lhs, rhs } => compare_ord(lhs, rhs, event, |a, b| a > b),
        RuntimeExpr::Le { lhs, rhs } => compare_ord(lhs, rhs, event, |a, b| a <= b),
        RuntimeExpr::Ge { lhs, rhs } => compare_ord(lhs, rhs, event, |a, b| a >= b),
        RuntimeExpr::In { lhs, rhs } => {
            let lhs = eval_value(lhs, event);
            rhs.iter().any(|item| eval_value(item, event) == lhs)
        }
        RuntimeExpr::StartsWith { lhs, rhs } => {
            to_string(eval_value(lhs, event)).starts_with(&to_string(eval_value(rhs, event)))
        }
        RuntimeExpr::EndsWith { lhs, rhs } => {
            to_string(eval_value(lhs, event)).ends_with(&to_string(eval_value(rhs, event)))
        }
        RuntimeExpr::Contains { lhs, rhs } => {
            to_string(eval_value(lhs, event)).contains(&to_string(eval_value(rhs, event)))
        }
        RuntimeExpr::Unsupported { .. } => false,
        _ => false,
    }
}

fn eval_eq(lhs: &RuntimeExpr, rhs: &RuntimeExpr, event: &IngestEvent) -> bool {
    if let Some(result) = eval_domain_eq(lhs, rhs, event) {
        return result;
    }
    eval_value(lhs, event) == eval_value(rhs, event)
}

// Support `n.dest.domain == "example.com"` by resolving the right-hand domain
// to IPv4 addresses and matching against the observed net destination IP.
fn eval_domain_eq(lhs: &RuntimeExpr, rhs: &RuntimeExpr, event: &IngestEvent) -> Option<bool> {
    if event.event_type != 3 || event.net_dst_ip == 0 {
        return None;
    }

    if let (Some(path), Some(domain)) = (field_path(lhs), string_lit(rhs)) {
        if is_domain_path(path) {
            return Some(domain_matches_dst_ip(domain, event.net_dst_ip));
        }
    }
    if let (Some(path), Some(domain)) = (field_path(rhs), string_lit(lhs)) {
        if is_domain_path(path) {
            return Some(domain_matches_dst_ip(domain, event.net_dst_ip));
        }
    }
    None
}

fn field_path(expr: &RuntimeExpr) -> Option<&str> {
    match expr {
        RuntimeExpr::Field { path } => Some(path.as_str()),
        _ => None,
    }
}

fn string_lit(expr: &RuntimeExpr) -> Option<&str> {
    match expr {
        RuntimeExpr::Str { value } => Some(value.as_str()),
        _ => None,
    }
}

fn is_domain_path(path: &str) -> bool {
    path == "domain" || path.ends_with(".domain")
}

fn domain_matches_dst_ip(domain: &str, dst_ip: u32) -> bool {
    resolve_domain_ipv4_cached(domain)
        .into_iter()
        .any(|resolved| resolved == dst_ip)
}

fn resolve_domain_ipv4_cached(domain: &str) -> Vec<u32> {
    let cache = DOMAIN_IP_CACHE.get_or_init(|| Mutex::new(HashMap::new()));
    let now = Instant::now();

    if let Ok(guard) = cache.lock() {
        if let Some((fetched_at, ips)) = guard.get(domain) {
            if now.duration_since(*fetched_at) <= DNS_CACHE_TTL {
                return ips.clone();
            }
        }
    }

    let mut resolved = Vec::new();
    if let Ok(addrs) = (domain, 0u16).to_socket_addrs() {
        for addr in addrs {
            if let IpAddr::V4(v4) = addr.ip() {
                let ip = u32::from(v4);
                if !resolved.contains(&ip) {
                    resolved.push(ip);
                }
            }
        }
    }

    if let Ok(mut guard) = cache.lock() {
        guard.insert(domain.to_string(), (Instant::now(), resolved.clone()));
    }

    resolved
}

// Compare two expressions after numeric coercion.
fn compare_ord(
    lhs: &RuntimeExpr,
    rhs: &RuntimeExpr,
    event: &IngestEvent,
    cmp: impl Fn(f64, f64) -> bool,
) -> bool {
    match (
        to_number(eval_value(lhs, event)),
        to_number(eval_value(rhs, event)),
    ) {
        (Some(a), Some(b)) => cmp(a, b),
        _ => false,
    }
}

// Evaluate expression in value context (bool/number/string/null).
fn eval_value(expr: &RuntimeExpr, event: &IngestEvent) -> Value {
    match expr {
        RuntimeExpr::Bool { value } => Value::Bool(*value),
        RuntimeExpr::Int { value } => Value::Number(*value as f64),
        RuntimeExpr::Float { value } => Value::Number(*value),
        RuntimeExpr::Str { value } => Value::String(value.clone()),
        RuntimeExpr::Field { path } => lookup_field(path, event),
        RuntimeExpr::Eq { .. }
        | RuntimeExpr::Ne { .. }
        | RuntimeExpr::Lt { .. }
        | RuntimeExpr::Gt { .. }
        | RuntimeExpr::Le { .. }
        | RuntimeExpr::Ge { .. }
        | RuntimeExpr::In { .. }
        | RuntimeExpr::StartsWith { .. }
        | RuntimeExpr::EndsWith { .. }
        | RuntimeExpr::Contains { .. }
        | RuntimeExpr::And { .. }
        | RuntimeExpr::Or { .. }
        | RuntimeExpr::Not { .. } => Value::Bool(eval_bool(expr, event)),
        RuntimeExpr::Unsupported { .. } => Value::Null,
    }
}

// Resolve known event field names into runtime values.
fn lookup_field(path: &str, event: &IngestEvent) -> Value {
    let key = path.rsplit('.').next().unwrap_or(path);
    match key {
        "ts_ns" => Value::Number(event.ts_ns as f64),
        "pid" => Value::Number(event.pid as f64),
        "uid" => Value::Number(event.uid as f64),
        "event_type" => Value::Number(event.event_type as f64),
        "vertex_id" => Value::Number(event.vertex_id as f64),
        "dst_vertex_id" => Value::Number(event.dst_vertex_id as f64),
        "direction" if event.event_type == 3 => Value::String("outbound".to_string()),
        "dst_ip" | "ip" if event.event_type == 3 => {
            Value::String(Ipv4Addr::from(event.net_dst_ip).to_string())
        }
        "dst_port" | "port" if event.event_type == 3 => Value::Number(event.net_dst_port as f64),
        "comm_id" => Value::Number(event.comm_id as f64),
        "risk_score" | "score" => Value::Number(event.risk_score as f64),
        _ => Value::Null,
    }
}

// Convert Value into number if possible.
fn to_number(value: Value) -> Option<f64> {
    match value {
        Value::Number(v) => Some(v),
        Value::Bool(v) => Some(if v { 1.0 } else { 0.0 }),
        Value::String(v) => v.parse::<f64>().ok(),
        Value::Null => None,
    }
}

// Convert Value into string for string operations.
fn to_string(value: Value) -> String {
    match value {
        Value::String(v) => v,
        Value::Number(v) => v.to_string(),
        Value::Bool(v) => {
            if v {
                "true".to_string()
            } else {
                "false".to_string()
            }
        }
        Value::Null => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use std::process::Command;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_runtime_ir_path() -> PathBuf {
        let ts = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time")
            .as_nanos();
        std::env::temp_dir().join(format!("olopa_runtime_ir_test_{ts}.json"))
    }

    fn temp_runtime_ir_dir() -> PathBuf {
        let ts = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time")
            .as_nanos();
        std::env::temp_dir().join(format!("olopa_runtime_ir_dir_{ts}"))
    }

    #[test]
    fn evaluates_numeric_rule() {
        let engine = RuntimeIrRuleEngine {
            program: RuntimeProgram {
                version: 1,
                rules: vec![RuntimeRule {
                    id: "r1".to_string(),
                    name: "r1".to_string(),
                    predicates: vec![RuntimeExpr::Eq {
                        lhs: Box::new(RuntimeExpr::Field {
                            path: "pid".to_string(),
                        }),
                        rhs: Box::new(RuntimeExpr::Int { value: 42 }),
                    }],
                    respond: RuntimeRespondPlan::default(),
                }],
            },
        };

        let event = IngestEvent {
            ts_ns: 0,
            pid: 42,
            uid: 0,
            event_type: 1,
            vertex_id: 42,
            dst_vertex_id: 0,
            net_dst_ip: 0,
            net_dst_port: 0,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.1,
        };
        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_id, "r1");
        assert!(!matches[0].enforce_block_egress);
    }

    #[test]
    fn loads_oilc_runtime_ir_json_file_and_matches_rule() {
        let path = temp_runtime_ir_path();
        let json = r#"{
  "version": 1,
  "rules": [
    {
      "id": "rule:0:pid_42",
      "name": "pid_42",
      "predicates": [
        {
          "op": "eq",
          "lhs": { "op": "field", "path": "pid" },
          "rhs": { "op": "int", "value": 42 }
        }
      ]
    }
  ]
}"#;
        fs::write(&path, json).expect("write runtime ir json");

        let engine = RuntimeIrRuleEngine::from_file(&path).expect("load runtime ir");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 42,
            uid: 0,
            event_type: 1,
            vertex_id: 42,
            dst_vertex_id: 0,
            net_dst_ip: 0,
            net_dst_port: 0,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.1,
        };

        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_id, "rule:0:pid_42");
        assert_eq!(matches[0].rule_name, "pid_42");
        assert!(!matches[0].enforce_block_egress);

        let _ = fs::remove_file(path);
    }

    #[test]
    fn loads_multi_unit_runtime_ir_and_merges_rules() {
        let path = temp_runtime_ir_path();
        let json = r#"{
  "version": 1,
  "units": [
    {
      "id": "unit-a",
      "program": {
        "version": 1,
        "rules": [
          {
            "id": "rule:pid_42",
            "name": "pid_42",
            "predicates": [
              {
                "op": "eq",
                "lhs": { "op": "field", "path": "pid" },
                "rhs": { "op": "int", "value": 42 }
              }
            ]
          }
        ]
      }
    },
    {
      "id": "unit-b",
      "program": {
        "version": 1,
        "rules": [
          {
            "id": "rule:uid_7",
            "name": "uid_7",
            "predicates": [
              {
                "op": "eq",
                "lhs": { "op": "field", "path": "uid" },
                "rhs": { "op": "int", "value": 7 }
              }
            ]
          }
        ]
      }
    }
  ]
}"#;
        fs::write(&path, json).expect("write runtime ir json");

        let engine = RuntimeIrRuleEngine::from_file(&path).expect("load runtime ir");
        assert_eq!(engine.rule_count(), 2);

        let event = IngestEvent {
            ts_ns: 0,
            pid: 42,
            uid: 7,
            event_type: 1,
            vertex_id: 0,
            dst_vertex_id: 0,
            net_dst_ip: 0,
            net_dst_port: 0,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.0,
        };
        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 2);
        assert_eq!(matches[0].rule_id, "rule:pid_42");
        assert_eq!(matches[1].rule_id, "rule:uid_7");
        assert!(!matches[0].enforce_block_egress);
        assert!(!matches[1].enforce_block_egress);

        let _ = fs::remove_file(path);
    }

    #[test]
    fn loads_runtime_ir_emitted_by_oilc_cli_and_matches() {
        let dir = temp_runtime_ir_dir();
        fs::create_dir_all(&dir).expect("create temp dir");

        let source_path = dir.join("rule.oil");
        let runtime_ir_path = dir.join("runtime-ir.json");
        let src = r#"
rule "pid_42" {
  from endpoint.process
  correlate process.spawn as p
  where p.pid == 42
  respond alert high
}
"#;
        fs::write(&source_path, src).expect("write oil source");

        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let repo_root = manifest_dir
            .parent()
            .and_then(|p| p.parent())
            .expect("repo root");
        let oilc_manifest = repo_root.join("oilc").join("Cargo.toml");

        let output = Command::new("cargo")
            .arg("run")
            .arg("--manifest-path")
            .arg(&oilc_manifest)
            .arg("--")
            .arg("--source")
            .arg(&source_path)
            .arg("--emit-runtime-ir")
            .arg(&runtime_ir_path)
            .arg("--mode")
            .arg("check")
            .current_dir(repo_root)
            .output()
            .expect("run oilc cli");
        assert!(
            output.status.success(),
            "oilc cli failed:\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );

        let engine = RuntimeIrRuleEngine::from_file(&runtime_ir_path).expect("load runtime ir");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 42,
            uid: 0,
            event_type: 1,
            vertex_id: 0,
            dst_vertex_id: 0,
            net_dst_ip: 0,
            net_dst_port: 0,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.0,
        };
        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_name, "pid_42");
        assert!(!matches[0].enforce_block_egress);

        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn loads_multi_source_runtime_ir_emitted_by_oilc_cli_and_matches_both_rules() {
        let dir = temp_runtime_ir_dir();
        fs::create_dir_all(&dir).expect("create temp dir");

        let source_a = dir.join("rule_a.oil");
        let source_b = dir.join("rule_b.oil");
        let runtime_ir_path = dir.join("runtime-ir.json");

        let src_a = r#"
rule "pid_42" {
  from endpoint.process
  correlate process.spawn as p
  where p.pid == 42
  respond alert high
}
"#;
        let src_b = r#"
rule "uid_7" {
  from endpoint.process
  correlate process.spawn as p
  where p.uid == 7
  respond alert medium
}
"#;
        fs::write(&source_a, src_a).expect("write source a");
        fs::write(&source_b, src_b).expect("write source b");

        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let repo_root = manifest_dir
            .parent()
            .and_then(|p| p.parent())
            .expect("repo root");
        let oilc_manifest = repo_root.join("oilc").join("Cargo.toml");

        let output = Command::new("cargo")
            .arg("run")
            .arg("--manifest-path")
            .arg(&oilc_manifest)
            .arg("--")
            .arg("--source")
            .arg(&source_a)
            .arg("--source")
            .arg(&source_b)
            .arg("--emit-runtime-ir")
            .arg(&runtime_ir_path)
            .arg("--mode")
            .arg("check")
            .current_dir(repo_root)
            .output()
            .expect("run oilc cli");
        assert!(
            output.status.success(),
            "oilc cli failed:\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );

        let engine = RuntimeIrRuleEngine::from_file(&runtime_ir_path).expect("load runtime ir");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 42,
            uid: 7,
            event_type: 1,
            vertex_id: 0,
            dst_vertex_id: 0,
            net_dst_ip: 0,
            net_dst_port: 0,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.0,
        };
        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 2);
        assert!(matches.iter().any(|m| m.rule_name == "pid_42"));
        assert!(matches.iter().any(|m| m.rule_name == "uid_7"));
        assert!(!matches.iter().any(|m| m.enforce_block_egress));

        let _ = fs::remove_dir_all(dir);
    }

    #[test]
    fn marks_block_egress_rules_for_enforcement() {
        let path = temp_runtime_ir_path();
        let json = r#"{
  "version": 1,
  "rules": [
    {
      "id": "rule:0:block_egress",
      "name": "block_egress",
      "predicates": [
        {
          "op": "eq",
          "lhs": { "op": "field", "path": "pid" },
          "rhs": { "op": "int", "value": 42 }
        }
      ],
      "respond": {
        "branches": [
          {
            "condition": null,
            "actions": [
              { "action": "alert", "severity": "critical" },
              { "action": "block_egress", "target": "n.dest.domain" }
            ]
          }
        ]
      }
    }
  ]
}"#;
        fs::write(&path, json).expect("write runtime ir json");

        let engine = RuntimeIrRuleEngine::from_file(&path).expect("load runtime ir");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 42,
            uid: 0,
            event_type: 3,
            vertex_id: 42,
            dst_vertex_id: 0,
            net_dst_ip: u32::from(Ipv4Addr::LOCALHOST),
            net_dst_port: 443,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.1,
        };

        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_name, "block_egress");
        assert!(matches[0].enforce_block_egress);

        let _ = fs::remove_file(path);
    }

    #[test]
    fn matches_domain_predicate_against_net_destination_ip() {
        let path = temp_runtime_ir_path();
        let json = r#"{
  "version": 1,
  "rules": [
    {
      "id": "rule:0:localhost_domain",
      "name": "localhost_domain",
      "predicates": [
        {
          "op": "eq",
          "lhs": { "op": "field", "path": "n.dest.domain" },
          "rhs": { "op": "str", "value": "localhost" }
        }
      ]
    }
  ]
}"#;
        fs::write(&path, json).expect("write runtime ir json");

        let engine = RuntimeIrRuleEngine::from_file(&path).expect("load runtime ir");
        let event = IngestEvent {
            ts_ns: 0,
            pid: 9001,
            uid: 0,
            event_type: 3,
            vertex_id: 9001,
            dst_vertex_id: 0,
            net_dst_ip: u32::from(Ipv4Addr::LOCALHOST),
            net_dst_port: 443,
            comm: [0; 16],
            comm_id: 0,
            risk_score: 0.2,
        };

        let matches = engine.evaluate_matches(&event);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].rule_name, "localhost_domain");

        let _ = fs::remove_file(path);
    }
}
